-- 仅补充业务表字段中文说明；保持字段类型、空值约束和默认值不变。
-- _prisma_migrations 由 Prisma 管理，不修改其结构。
ALTER TABLE `Account` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `Account` MODIFY COLUMN `userId` varchar(191) NOT NULL COMMENT '关联用户ID';
ALTER TABLE `Account` MODIFY COLUMN `type` varchar(64) NOT NULL COMMENT '账号类型';
ALTER TABLE `Account` MODIFY COLUMN `provider` varchar(191) NOT NULL COMMENT '身份提供方';
ALTER TABLE `Account` MODIFY COLUMN `providerAccountId` varchar(191) NOT NULL COMMENT '提供方账号ID';
ALTER TABLE `Account` MODIFY COLUMN `refresh_token` text NULL COMMENT 'OAuth刷新令牌';
ALTER TABLE `Account` MODIFY COLUMN `access_token` text NULL COMMENT 'OAuth访问令牌';
ALTER TABLE `Account` MODIFY COLUMN `expires_at` int NULL COMMENT '访问令牌到期时间戳';
ALTER TABLE `Account` MODIFY COLUMN `token_type` varchar(64) NULL COMMENT '令牌类型';
ALTER TABLE `Account` MODIFY COLUMN `scope` text NULL COMMENT '授权范围';
ALTER TABLE `Account` MODIFY COLUMN `id_token` text NULL COMMENT 'OIDC身份令牌';
ALTER TABLE `Account` MODIFY COLUMN `session_state` varchar(191) NULL COMMENT '提供方会话状态';
ALTER TABLE `AiGeneration` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `AiGeneration` MODIFY COLUMN `taskId` varchar(191) NOT NULL COMMENT '报告任务ID';
ALTER TABLE `AiGeneration` MODIFY COLUMN `placeholderId` varchar(191) NULL COMMENT '关联占位符ID，可为空';
ALTER TABLE `AiGeneration` MODIFY COLUMN `promptTemplateKey` varchar(191) NOT NULL COMMENT '提示词模板标识';
ALTER TABLE `AiGeneration` MODIFY COLUMN `inputSnapshotJson` json NOT NULL COMMENT '生成输入快照';
ALTER TABLE `AiGeneration` MODIFY COLUMN `provider` varchar(191) NOT NULL COMMENT 'AI服务提供方';
ALTER TABLE `AiGeneration` MODIFY COLUMN `model` varchar(191) NOT NULL COMMENT 'AI模型名称';
ALTER TABLE `AiGeneration` MODIFY COLUMN `outputText` longtext NOT NULL COMMENT 'AI原始输出';
ALTER TABLE `AiGeneration` MODIFY COLUMN `acceptedText` longtext NULL COMMENT '审核采纳的文本';
ALTER TABLE `AiGeneration` MODIFY COLUMN `createdById` varchar(191) NOT NULL COMMENT '创建人ID';
ALTER TABLE `AiGeneration` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `DataSource` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `DataSource` MODIFY COLUMN `name` varchar(191) NOT NULL COMMENT '数据源名称';
ALTER TABLE `DataSource` MODIFY COLUMN `type` enum('MYSQL','OCEANBASE','ORACLE','SQL_SERVER','REST_API') NOT NULL COMMENT '数据源类型';
ALTER TABLE `DataSource` MODIFY COLUMN `status` enum('ACTIVE','DISABLED','ERROR') NOT NULL DEFAULT 'ACTIVE' COMMENT '数据源启用状态';
ALTER TABLE `DataSource` MODIFY COLUMN `host` varchar(255) NULL COMMENT '数据库主机地址';
ALTER TABLE `DataSource` MODIFY COLUMN `port` int NULL COMMENT '数据库端口';
ALTER TABLE `DataSource` MODIFY COLUMN `databaseName` varchar(191) NULL COMMENT '数据库名称';
ALTER TABLE `DataSource` MODIFY COLUMN `username` varchar(191) NULL COMMENT '连接用户名';
ALTER TABLE `DataSource` MODIFY COLUMN `encryptedPassword` text NULL COMMENT '加密后的连接密码';
ALTER TABLE `DataSource` MODIFY COLUMN `encryptionKeyVersion` varchar(64) NULL COMMENT '加密密钥版本';
ALTER TABLE `DataSource` MODIFY COLUMN `optionsJson` json NULL COMMENT '连接配置选项';
ALTER TABLE `DataSource` MODIFY COLUMN `createdById` varchar(191) NOT NULL COMMENT '创建人ID';
ALTER TABLE `DataSource` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `DataSource` MODIFY COLUMN `updatedAt` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `FillInstance` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `FillInstance` MODIFY COLUMN `assignmentId` varchar(191) NOT NULL COMMENT '页面分配记录ID';
ALTER TABLE `FillInstance` MODIFY COLUMN `taskId` varchar(191) NOT NULL COMMENT '报告任务ID';
ALTER TABLE `FillInstance` MODIFY COLUMN `templateSlideId` varchar(191) NOT NULL COMMENT '模板页ID';
ALTER TABLE `FillInstance` MODIFY COLUMN `assigneeId` varchar(191) NOT NULL COMMENT '填报人ID';
ALTER TABLE `FillInstance` MODIFY COLUMN `status` enum('NOT_STARTED','IN_PROGRESS','SUBMITTED','RETURNED','REVIEWED') NOT NULL DEFAULT 'NOT_STARTED' COMMENT '填报实例状态';
ALTER TABLE `FillInstance` MODIFY COLUMN `version` int NOT NULL DEFAULT '0' COMMENT '填报实例乐观锁版本号';
ALTER TABLE `FillInstance` MODIFY COLUMN `submittedAt` datetime(3) NULL COMMENT '提交时间';
ALTER TABLE `FillInstance` MODIFY COLUMN `reviewedAt` datetime(3) NULL COMMENT '审核时间';
ALTER TABLE `FillInstance` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `FillInstance` MODIFY COLUMN `updatedAt` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `FinalValue` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `FinalValue` MODIFY COLUMN `taskId` varchar(191) NOT NULL COMMENT '报告任务ID';
ALTER TABLE `FinalValue` MODIFY COLUMN `placeholderId` varchar(191) NOT NULL COMMENT '模板占位符ID';
ALTER TABLE `FinalValue` MODIFY COLUMN `valueText` longtext NOT NULL COMMENT '审核确定的最终文本';
ALTER TABLE `FinalValue` MODIFY COLUMN `resolutionType` enum('SELECTED_SUBMISSION','MANUAL') NOT NULL COMMENT '最终值确定方式';
ALTER TABLE `FinalValue` MODIFY COLUMN `selectedSubmittedValueId` varchar(191) NULL COMMENT '被选中的提交值ID';
ALTER TABLE `FinalValue` MODIFY COLUMN `sourceSnapshotJson` json NULL COMMENT '最终值来源快照';
ALTER TABLE `FinalValue` MODIFY COLUMN `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号';
ALTER TABLE `FinalValue` MODIFY COLUMN `decidedById` varchar(191) NOT NULL COMMENT '最终值决定人ID';
ALTER TABLE `FinalValue` MODIFY COLUMN `decidedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '最终值决定时间';
ALTER TABLE `FinalValue` MODIFY COLUMN `updatedAt` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `taskId` varchar(191) NOT NULL COMMENT '报告任务ID';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `type` enum('PPTX','PDF','PNG') NOT NULL COMMENT '生成文件类型';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `status` enum('PENDING','PROCESSING','COMPLETED','FAILED') NOT NULL DEFAULT 'PENDING' COMMENT '生成状态';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `storedFileId` varchar(191) NULL COMMENT '存储文件ID';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `valuesSnapshotJson` json NOT NULL COMMENT '生成时的最终值快照';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `idempotencyKey` varchar(191) NOT NULL COMMENT '生成请求幂等键';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `errorCode` varchar(64) NULL COMMENT '生成失败错误码';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `createdById` varchar(191) NOT NULL COMMENT '创建人ID';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `GeneratedFile` MODIFY COLUMN `completedAt` datetime(3) NULL COMMENT '生成完成时间';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `dataSourceId` varchar(191) NOT NULL COMMENT '数据源ID';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `code` varchar(191) NOT NULL COMMENT '指标编码';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `name` varchar(191) NOT NULL COMMENT '指标名称';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `description` text NULL COMMENT '指标说明';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `valueType` enum('STRING','NUMBER','BOOLEAN','DATE','JSON') NOT NULL COMMENT '指标值类型';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `unit` varchar(64) NULL COMMENT '指标单位';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `writable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否允许修改源指标';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `queryConfigJson` json NOT NULL COMMENT '指标查询配置';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `updateConfigJson` json NULL COMMENT '指标更新配置';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `MetricDefinition` MODIFY COLUMN `updatedAt` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `MetricValue` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `MetricValue` MODIFY COLUMN `metricDefinitionId` varchar(191) NOT NULL COMMENT '指标定义ID';
ALTER TABLE `MetricValue` MODIFY COLUMN `period` char(7) NOT NULL COMMENT '数据月份，格式YYYY-MM';
ALTER TABLE `MetricValue` MODIFY COLUMN `dimensionsHash` char(64) NOT NULL COMMENT '指标维度组合摘要';
ALTER TABLE `MetricValue` MODIFY COLUMN `dimensionsJson` json NULL COMMENT '指标维度数据';
ALTER TABLE `MetricValue` MODIFY COLUMN `valueText` longtext NOT NULL COMMENT '指标文本值';
ALTER TABLE `MetricValue` MODIFY COLUMN `valueNumber` decimal(65,18) NULL COMMENT '指标数值';
ALTER TABLE `MetricValue` MODIFY COLUMN `sourceVersion` varchar(191) NULL COMMENT '源数据库记录版本';
ALTER TABLE `MetricValue` MODIFY COLUMN `sourceUpdatedAt` datetime(3) NULL COMMENT '源数据库更新时间';
ALTER TABLE `MetricValue` MODIFY COLUMN `version` int NOT NULL DEFAULT '0' COMMENT '平台指标镜像版本号';
ALTER TABLE `MetricValue` MODIFY COLUMN `fetchedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '指标抓取时间';
ALTER TABLE `MetricValueHistory` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `MetricValueHistory` MODIFY COLUMN `metricValueId` varchar(191) NOT NULL COMMENT '指标值ID';
ALTER TABLE `MetricValueHistory` MODIFY COLUMN `oldValueJson` json NOT NULL COMMENT '变更前指标值快照';
ALTER TABLE `MetricValueHistory` MODIFY COLUMN `newValueJson` json NOT NULL COMMENT '变更后指标值快照';
ALTER TABLE `MetricValueHistory` MODIFY COLUMN `reason` text NOT NULL COMMENT '指标修改原因';
ALTER TABLE `MetricValueHistory` MODIFY COLUMN `operatorId` varchar(191) NOT NULL COMMENT '操作人ID';
ALTER TABLE `MetricValueHistory` MODIFY COLUMN `expectedVersion` int NOT NULL COMMENT '修改时预期的旧版本号';
ALTER TABLE `MetricValueHistory` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `OperationLog` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `OperationLog` MODIFY COLUMN `actorId` varchar(191) NOT NULL COMMENT '操作用户ID';
ALTER TABLE `OperationLog` MODIFY COLUMN `action` varchar(64) NOT NULL COMMENT '操作动作编码';
ALTER TABLE `OperationLog` MODIFY COLUMN `resourceType` varchar(64) NOT NULL COMMENT '操作资源类型';
ALTER TABLE `OperationLog` MODIFY COLUMN `resourceId` varchar(191) NOT NULL COMMENT '操作资源ID';
ALTER TABLE `OperationLog` MODIFY COLUMN `taskId` varchar(191) NULL COMMENT '关联报告任务ID';
ALTER TABLE `OperationLog` MODIFY COLUMN `beforeJson` json NULL COMMENT '操作前数据快照';
ALTER TABLE `OperationLog` MODIFY COLUMN `afterJson` json NULL COMMENT '操作后数据快照';
ALTER TABLE `OperationLog` MODIFY COLUMN `metadataJson` json NULL COMMENT '操作附加信息';
ALTER TABLE `OperationLog` MODIFY COLUMN `correlationId` varchar(191) NOT NULL COMMENT '请求关联追踪ID';
ALTER TABLE `OperationLog` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `fillInstanceId` varchar(191) NOT NULL COMMENT '填报实例ID';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `placeholderId` varchar(191) NOT NULL COMMENT '模板占位符ID';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `sourceType` enum('DATABASE_METRIC','MANUAL_TEXT','AI_GENERATED','EXPRESSION','API') NOT NULL COMMENT '填报值来源类型';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `metricDefinitionId` varchar(191) NULL COMMENT '绑定的指标定义ID';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `metricPeriod` char(7) NULL COMMENT '绑定指标月份，格式YYYY-MM';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `manualValue` text NULL COMMENT '人工填报文本';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `aiGenerationId` varchar(191) NULL COMMENT 'AI生成记录ID';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `formatOptionsJson` json NULL COMMENT '值格式化选项';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `version` int NOT NULL DEFAULT '0' COMMENT '绑定记录乐观锁版本号';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `updatedById` varchar(191) NOT NULL COMMENT '更新人ID';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `updatedAt` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `PlaceholderBinding` MODIFY COLUMN `sourceSnapshotJson` json NULL COMMENT '数据来源快照';
ALTER TABLE `ReportTask` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `ReportTask` MODIFY COLUMN `name` varchar(191) NOT NULL COMMENT '报告任务名称';
ALTER TABLE `ReportTask` MODIFY COLUMN `templateId` varchar(191) NOT NULL COMMENT '使用的模板ID';
ALTER TABLE `ReportTask` MODIFY COLUMN `reportPeriod` char(7) NOT NULL COMMENT '报告月份，格式YYYY-MM';
ALTER TABLE `ReportTask` MODIFY COLUMN `status` enum('DRAFT','FILLING','REVIEWING','COMPLETED','EXPORTED') NOT NULL DEFAULT 'DRAFT' COMMENT '报告任务状态';
ALTER TABLE `ReportTask` MODIFY COLUMN `collectorId` varchar(191) NOT NULL COMMENT '收集人ID';
ALTER TABLE `ReportTask` MODIFY COLUMN `version` int NOT NULL DEFAULT '0' COMMENT '报告任务乐观锁版本号';
ALTER TABLE `ReportTask` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `ReportTask` MODIFY COLUMN `updatedAt` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `name` varchar(191) NOT NULL COMMENT '模板名称';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `version` int NOT NULL COMMENT '模板业务版本号';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `status` enum('UPLOADING','PARSING','READY','PARSE_FAILED','ARCHIVED') NOT NULL DEFAULT 'UPLOADING' COMMENT '模板解析状态';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `sourceFileId` varchar(191) NOT NULL COMMENT '源文件ID';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `sha256` char(64) NOT NULL COMMENT '模板源文件SHA-256摘要';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `parserVersion` varchar(64) NULL COMMENT 'PPT解析器版本';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `createdById` varchar(191) NOT NULL COMMENT '创建人ID';
ALTER TABLE `ReportTemplate` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `Role` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `Role` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '角色编码';
ALTER TABLE `Role` MODIFY COLUMN `name` varchar(191) NOT NULL COMMENT '角色名称';
ALTER TABLE `Role` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `Session` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `Session` MODIFY COLUMN `sessionToken` varchar(191) NOT NULL COMMENT '数据库会话令牌';
ALTER TABLE `Session` MODIFY COLUMN `userId` varchar(191) NOT NULL COMMENT '会话用户ID';
ALTER TABLE `Session` MODIFY COLUMN `expires` datetime(3) NOT NULL COMMENT '会话到期时间';
ALTER TABLE `SlideAssignment` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `SlideAssignment` MODIFY COLUMN `taskId` varchar(191) NOT NULL COMMENT '报告任务ID';
ALTER TABLE `SlideAssignment` MODIFY COLUMN `templateSlideId` varchar(191) NOT NULL COMMENT '模板页ID';
ALTER TABLE `SlideAssignment` MODIFY COLUMN `assigneeId` varchar(191) NOT NULL COMMENT '填报人ID';
ALTER TABLE `SlideAssignment` MODIFY COLUMN `createdById` varchar(191) NOT NULL COMMENT '分配操作人ID';
ALTER TABLE `SlideAssignment` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `StoredFile` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `StoredFile` MODIFY COLUMN `category` enum('TEMPLATE','PREVIEW','GENERATED','TEMP') NOT NULL COMMENT '存储文件用途';
ALTER TABLE `StoredFile` MODIFY COLUMN `storagePath` varchar(768) NOT NULL COMMENT '文件相对存储路径';
ALTER TABLE `StoredFile` MODIFY COLUMN `originalFilename` varchar(255) NOT NULL COMMENT '上传时的原始文件名';
ALTER TABLE `StoredFile` MODIFY COLUMN `mimeType` varchar(191) NOT NULL COMMENT '文件MIME类型';
ALTER TABLE `StoredFile` MODIFY COLUMN `sizeBytes` bigint NOT NULL COMMENT '文件大小（字节）';
ALTER TABLE `StoredFile` MODIFY COLUMN `sha256` char(64) NOT NULL COMMENT '文件SHA-256摘要';
ALTER TABLE `StoredFile` MODIFY COLUMN `createdById` varchar(191) NOT NULL COMMENT '创建人ID';
ALTER TABLE `StoredFile` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `fillInstanceId` varchar(191) NOT NULL COMMENT '填报实例ID';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `placeholderId` varchar(191) NOT NULL COMMENT '模板占位符ID';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `valueText` longtext NOT NULL COMMENT '已提交的不可变文本值';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `sourceType` enum('DATABASE_METRIC','MANUAL_TEXT','AI_GENERATED','EXPRESSION','API') NOT NULL COMMENT '数据来源类型';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `sourceSnapshotJson` json NULL COMMENT '提交时来源快照';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `bindingSnapshotJson` json NOT NULL COMMENT '提交时绑定配置快照';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `submittedById` varchar(191) NOT NULL COMMENT '提交人ID';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `submittedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '提交时间';
ALTER TABLE `SubmittedValue` MODIFY COLUMN `submissionRevision` int NOT NULL COMMENT '提交修订次数';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `slideId` varchar(191) NOT NULL COMMENT '所属模板页ID';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `key` varchar(191) NOT NULL COMMENT '占位符变量名';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `occurrenceIndex` int NOT NULL COMMENT '同名占位符出现序号';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `shapeId` int NOT NULL COMMENT 'PPT图形ID';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `shapeName` varchar(191) NULL COMMENT 'PPT图形名称';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `shapeType` varchar(64) NOT NULL COMMENT 'PPT图形类型';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `containerType` varchar(64) NOT NULL COMMENT '占位符容器类型';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `paragraphIndex` int NULL COMMENT '文本段落序号';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `startRunIndex` int NULL COMMENT '起始文本片段序号';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `startOffset` int NULL COMMENT '起始片段内字符偏移';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `endRunIndex` int NULL COMMENT '结束文本片段序号';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `endOffset` int NULL COMMENT '结束片段内字符偏移';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `tableRow` int NULL COMMENT '表格行序号';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `tableColumn` int NULL COMMENT '表格列序号';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `xEmu` bigint NOT NULL COMMENT '图形左上角横坐标（EMU）';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `yEmu` bigint NOT NULL COMMENT '图形左上角纵坐标（EMU）';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `widthEmu` bigint NOT NULL COMMENT '图形宽度（EMU）';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `heightEmu` bigint NOT NULL COMMENT '图形高度（EMU）';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `originalText` text NOT NULL COMMENT '占位符原始文本';
ALTER TABLE `TemplatePlaceholder` MODIFY COLUMN `styleJson` json NULL COMMENT '占位符文字样式快照';
ALTER TABLE `TemplateSlide` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `TemplateSlide` MODIFY COLUMN `templateId` varchar(191) NOT NULL COMMENT '报告模板ID';
ALTER TABLE `TemplateSlide` MODIFY COLUMN `slideIndex` int NOT NULL COMMENT '模板页序号，从0开始';
ALTER TABLE `TemplateSlide` MODIFY COLUMN `widthEmu` bigint NOT NULL COMMENT '页面宽度（EMU）';
ALTER TABLE `TemplateSlide` MODIFY COLUMN `heightEmu` bigint NOT NULL COMMENT '页面高度（EMU）';
ALTER TABLE `TemplateSlide` MODIFY COLUMN `previewFileId` varchar(191) NULL COMMENT '预览文件ID';
ALTER TABLE `TemplateSlide` MODIFY COLUMN `metadataJson` json NULL COMMENT '页面解析元数据';
ALTER TABLE `User` MODIFY COLUMN `id` varchar(191) NOT NULL COMMENT '记录主键';
ALTER TABLE `User` MODIFY COLUMN `email` varchar(191) NULL COMMENT '电子邮箱，可为空';
ALTER TABLE `User` MODIFY COLUMN `name` varchar(191) NULL COMMENT '用户显示名称';
ALTER TABLE `User` MODIFY COLUMN `emailVerified` datetime(3) NULL COMMENT '邮箱验证时间';
ALTER TABLE `User` MODIFY COLUMN `image` text NULL COMMENT '用户头像地址';
ALTER TABLE `User` MODIFY COLUMN `status` enum('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE' COMMENT '用户账号状态';
ALTER TABLE `User` MODIFY COLUMN `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
ALTER TABLE `User` MODIFY COLUMN `updatedAt` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `User` MODIFY COLUMN `username` varchar(191) NOT NULL COMMENT '登录用户名';
ALTER TABLE `UserCredential` MODIFY COLUMN `userId` varchar(191) NOT NULL COMMENT '用户ID';
ALTER TABLE `UserCredential` MODIFY COLUMN `passwordHash` varchar(255) NOT NULL COMMENT '带随机盐的密码哈希';
ALTER TABLE `UserCredential` MODIFY COLUMN `failedAttempts` int NOT NULL DEFAULT '0' COMMENT '连续登录失败次数';
ALTER TABLE `UserCredential` MODIFY COLUMN `lockedUntil` datetime(3) NULL COMMENT '账号锁定截止时间';
ALTER TABLE `UserCredential` MODIFY COLUMN `updatedAt` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `UserRole` MODIFY COLUMN `userId` varchar(191) NOT NULL COMMENT '被授权用户ID';
ALTER TABLE `UserRole` MODIFY COLUMN `roleId` varchar(191) NOT NULL COMMENT '角色ID';
ALTER TABLE `UserRole` MODIFY COLUMN `assignedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '角色授予时间';
ALTER TABLE `VerificationToken` MODIFY COLUMN `identifier` varchar(191) NOT NULL COMMENT '验证对象标识';
ALTER TABLE `VerificationToken` MODIFY COLUMN `token` varchar(191) NOT NULL COMMENT '一次性验证令牌';
ALTER TABLE `VerificationToken` MODIFY COLUMN `expires` datetime(3) NOT NULL COMMENT '令牌到期时间';
